apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
  namespace: hipster
spec:
  strategy: production
  agent:
    strategy: DaemonSet
  collector:
    maxReplicas: 5
  query:
    serviceType: NodePort
  sampling:
    options:
      default_strategy:
        type: probabilistic
        param: 100
  ingester:
    maxReplicas: 8
