apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: kafka
  namespace: kafka
spec:
  kafka:
    version: 2.5.0
    replicas: 1
    template:
      pod:
        securityContext:
          runAsUser: 0
          fsGroup: 0
    listeners:
      external:
        type: nodeport
        tls: false
        overrides:
          bootstrap:
            nodePort: 39092
          brokers:
            - broker: 0
              nodePort: 39000
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      log.message.format.version: "2.5"
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 10Gi
        deleteClaim: false
  zookeeper:
    template:
      pod:
        securityContext:
          runAsUser: 0
          fsGroup: 0
    replicas: 1
    storage:
      type: persistent-claim
      size: 10Gi
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}


